services:
  eureka-server:
    build: ./eureka-server
    ports: ["8761:8761"]
  gateway:
    build: ./gateway
    ports: ["8080:8080"]
    depends_on: [eureka-server]
  order-service-1:
    build: ./order-service
    environment: ["SERVER_PORT=8081"]
    depends_on: [eureka-server]
  order-service-2:
    build: ./order-service
    environment: ["SERVER_PORT=8083"]
    depends_on: [eureka-server]
  inventory-service:
    build: ./inventory-service
    environment: ["SERVER_PORT=8082"]
    depends_on: [eureka-server]
