server: { port: 8081 }
spring.application.name: order-service
eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address: true
management.endpoints.web.exposure.include: health,info,metrics
